### ISSUE TITLE
The segment is not skipped at the beginning of a video when shared from Yatse

### ISSUE THREAD

**Issue by ape364** [siku2/script.service.sponsorblock#15]
Hello. First of all, thanks for such a great thing! :)

But I'm facing this issue with this video https://youtu.be/G51PJ5KWAnc
YouTube Vanced on my mobile phone works well.
Here are the [logs](https://gist.github.com/ape364/0f193dbeb024e679e611cc555a8da844)

I see an unhandled exception:

```
2020-11-19 22:44:16.103 T:1268760800   ERROR: Exception in thread Checkpoint Listener:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 148, in __t_event_loop
                                                cp_reached = self.__idle()
                                              File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 109, in __idle
                                                return self.__sleep_until(cp)
                                              File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 93, in __sleep_until
                                                wait_for = (target_time - self._get_current_time()) / self._playback_speed
                                              File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 86, in _get_current_time
                                                return self.getTime()
                                            RuntimeError: XBMC is not playing any media file
```

probably it occurs cuz the ad starts from the very beginning of the video

_Originally posted by @ape364 in https://github.com/siku2/script.service.sponsorblock/issues/11#issuecomment-730537699_

**Comment by siku2** [comment]
Okay I tried a different approach now. Will create a new release (0.2.3) in a few minutes.
Please let me know whether that actually fixed it.

**Comment by ape364** [comment]
How can I update the add-on? I'm trying to update, but it's still version 0.2.2.

**Comment by siku2** [comment]
> How can I update the add-on? I'm trying to update, but it's still version 0.2.2.

Sorry about that, it seems like the automatic release failed. I'll do it manually so you should a new release soon.

**Comment by ape364** [comment]
I've tried again at the same video - no changes.

**Comment by siku2** [comment]
Can you update the logs? I added some additional information for this case.

**Comment by ape364** [comment]
https://gist.github.com/ape364/6ae961f5a0eb861372b5fbc05f90d8ac

**Comment by siku2** [comment]
After looking at the logfile again, I believe this was actually the same issue as #17.
Closing this because that issue has been resolved some time ago.
