### ISSUE TITLE
Doesn't work with upstream kodi

### ISSUE THREAD

**Issue by innerspacepilot** [siku2/script.service.sponsorblock#33]
Hello!
Thanks for the plugin ! :)
It doesn't work with upstream kodi with the following error:

2022-04-25 13:34:41.775 T:12172   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmcgui' has no attribute 'ACTION_NAV_BACK'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/script.service.sponsorblock/service.py", line 1, in <module>
                                                       from resources.lib.monitor import Monitor
                                                     File "/home/kodi/.kodi/addons/script.service.sponsorblock/resources/lib/monitor.py", line 6, in <module>
                                                       from .player_listener import PlayerListener
                                                     File "/home/kodi/.kodi/addons/script.service.sponsorblock/resources/lib/player_listener.py", line 7, in <module>
                                                       from .gui.sponsor_skipped import SponsorSkipped
                                                     File "/home/kodi/.kodi/addons/script.service.sponsorblock/resources/lib/gui/sponsor_skipped.py", line 11, in <module>
                                                       _CLOSE_ACTIONS = {xbmcgui.ACTION_NAV_BACK, xbmcgui.ACTION_PREVIOUS_MENU}
                                                   AttributeError: module 'xbmcgui' has no attribute 'ACTION_NAV_BACK'
                                                   -->End of Python script error report<--

**Comment by innerspacepilot** [comment]
can be fixed with:
```
11c11
< _CLOSE_ACTIONS = {xbmcgui.ACTION_NAV_BACK, xbmcgui.ACTION_PREVIOUS_MENU}
---
> _CLOSE_ACTIONS = {92,10}
```

**Comment by innerspacepilot** [comment]
oops. that seems to be fixed in kodi itself. no code changes needed here.
