### ISSUE TITLE
sponsorblock v0.5.0 has stopped working

### ISSUE THREAD

**Issue by cracklejoy** [siku2/script.service.sponsorblock#54]
All I get is an error when Kodi starts saying to check the logs.  This is what I'm seeing while the addon does not work anymore.

```
2023-06-26 19:12:11.269 T:139999039166208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                 
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                           
                                            Error Type: <type 'exceptions.ImportError'>                                                                                
                                            Error Contents: cannot import name ABC                                                                                     
                                            Traceback (most recent call last):                                                                                         
                                              File "/storage/.kodi/addons/script.service.sponsorblock/service.py", line 1, in <module>                                 
                                                from resources.lib.monitor import Monitor                                                                              
                                              File "/storage/.kodi/addons/script.service.sponsorblock/resources/lib/monitor.py", line 4, in <module>                   
                                                from .apis.api_factory import get_api                                                                                  
                                              File "/storage/.kodi/addons/script.service.sponsorblock/resources/lib/apis/api_factory.py", line 3, in <module>          
                                                from .abstract_api import AbstractApi                                                                                  
                                              File "/storage/.kodi/addons/script.service.sponsorblock/resources/lib/apis/abstract_api.py", line 1, in <module>         
                                                from abc import ABC, abstractmethod                                                                                    
                                            ImportError: cannot import name ABC                                                                                        
                                            -->End of Python script error report<--                                                                                    
2023-06-26 19:12:11.270 T:139999039166208   DEBUG: onExecutionDone(13, /storage/.kodi/addons/script.service.sponsorblock/service.py)   
```

**Comment by mysterious-roman-dodecahedron** [comment]
I believe Pitsi describes the cause of this in their issue [post](https://github.com/siku2/script.service.sponsorblock/issues/55). For the time being, I have found that installing the old [0.4.0 ](https://github.com/siku2/script.service.sponsorblock/releases/tag/v0.4.0)sponsorblock service via zip file at least allows you to retain the core functionality of the plugin.
